### ISSUE TITLE
Refactoring: Remove git and add dependency to while-true-do.git

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-role-cli-tools#1]
### Type of Report

Enhancement

### Actual behaviour

Git is not a real cli-tool but more common tool, which will be used from multiple roles.
The role installs git always and other roles cannot use git alone to checkout.

### Expected behaviour

Other roles will depend on while-true-do.git and this role should do the same.

**Comment by Cinux90** [comment]
I'll take care
